# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 01:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('carrera', models.TextField()),
                ('cicloIngreso', models.DateField()),
                ('telefono', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.TextField()),
                ('codigo', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('horas', models.TimeField()),
                ('codigo', models.CharField(max_length=10)),
                ('departamento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MateriaAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Alumno')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Maestro')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaCiclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('aula', models.CharField(max_length=10)),
                ('ciclo', models.DateField()),
                ('IDMaestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Maestro')),
                ('IDMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Materia')),
            ],
        ),
        migrations.AddField(
            model_name='materiaalumno',
            name='materiaCiclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.MateriaCiclo'),
        ),
    ]
