# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-25 21:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('carrera', models.TextField()),
                ('cicloIngreso', models.DateField()),
                ('telefono', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('horas', models.IntegerField()),
                ('departamento', models.TextField()),
                ('hora', models.TimeField()),
                ('aula', models.CharField(max_length=10)),
                ('ciclo', models.CharField(max_length=15)),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CursoAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.TextField()),
                ('codigo', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='TareaAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('entrega', models.DateTimeField(blank=True, null=True)),
                ('comentario', models.TextField(default='Ninguno')),
                ('estatus', models.IntegerField(default=1)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='TareaCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('fechaInicio', models.DateField(auto_now=True)),
                ('fechaFin', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='tareaalumno',
            name='tareaCurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.TareaCurso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Maestro'),
        ),
    ]
