# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-17 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0002_auto_20181115_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fechaInicio', models.DateField(auto_now=True)),
                ('fechaFin', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='materiaciclo',
            old_name='IDMaestro',
            new_name='maestro',
        ),
        migrations.RenameField(
            model_name='materiaciclo',
            old_name='IDMateria',
            new_name='materia',
        ),
        migrations.RemoveField(
            model_name='materiaalumno',
            name='maestro',
        ),
        migrations.RemoveField(
            model_name='materiaalumno',
            name='materia',
        ),
        migrations.AddField(
            model_name='materiaciclo',
            name='codigo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maestro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Usuario'),
        ),
        migrations.AlterField(
            model_name='materiaciclo',
            name='ciclo',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='tarea',
            name='materiaCiclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.MateriaCiclo'),
        ),
    ]
