# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-25 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0002_auto_20181125_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoalumno',
            name='calificacion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
