# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-17 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0003_auto_20181116_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaalumno',
            name='calificacion',
            field=models.FloatField(null=True),
        ),
    ]
