# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-26 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0004_auto_20181125_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
    ]
