# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-17 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0004_auto_20181116_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField(null=True)),
                ('entrega', models.DateTimeField(null=True)),
                ('comentario', models.TextField(default='Ninguno')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Alumno')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Tarea')),
            ],
        ),
    ]
