# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-26 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0005_auto_20181126_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='departamento',
        ),
    ]
